df.pa <- dget("df.txt")
png(file="plot3.png")
plot(df.pa$datetime, df.pa$Sub_metering_1, xlab="", ylab="Energy sub metering", main="", type="l")
lines(df.pa$datetime, df.pa$Sub_metering_2, col='red')
lines(df.pa$datetime, df.pa$Sub_metering_3, col='blue')
legend('topright',,c('Sub_metering_1','Sub_metering_2','Sub_metering_3'), lty=1,col=c('black','red','blue'))
dev.off()
